import { useState, useEffect } from "react"
import { useLocation } from "react-router-dom"
import { Camera, MessageCircle, Store, User } from "lucide-react"
import ImageUpload from "../components/ImageUpload"
import SearchResults from "../components/SearchResults"
import ChatAssistant from "../components/ChatAssistant"

function Demo() {
  const location = useLocation()
    const [activeTab, setActiveTab] = useState("search")
      const [userType, setUserType] = useState("buyer")
        const [searchResults, setSearchResults] = useState([])
          const [imageAnalysis, setImageAnalysis] = useState(null)

            useEffect(() => {
                const params = new URLSearchParams(location.search)
                    if (params.get("tab") === "chat") setActiveTab("chat")
                      }, [location])

                        return (
                            <div className="animate-fadeIn">

                                  {/* Header */}
                                        <div
                                                className="sticky top-0 z-40 bg-white px-4 py-3"
                                                        style={{ borderBottom: "1px solid var(--border-color)", boxShadow: "var(--box-shadow)" }}
                                                              >
                                                                      <div className="flex items-center justify-between mb-3">
                                                                                <h2 className="text-base font-semibold m-0" style={{ color: "var(--text-color)" }}>
                                                                                            AI Features
                                                                                                      </h2>
                                                                                                                {/* User type toggle */}
                                                                                                                          <div
                                                                                                                                      className="flex items-center gap-1 rounded-full p-1"
                                                                                                                                                  style={{ background: "#f5f0f0", border: "1px solid var(--border-color)" }}
                                                                                                                                                            >
                                                                                                                                                                        <button
                                                                                                                                                                                      onClick={() => setUserType("buyer")}
                                                                                                                                                                                                    className="flex items-center gap-1 text-xs px-3 py-1 rounded-full font-medium transition-all"
                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                  background: userType === "buyer" ? "var(--accent-color)" : "transparent",
                                                                                                                                                                                                                                                  color: userType === "buyer" ? "#fff" : "var(--text-color-2)"
                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                          <User size={12} /> Buyer
                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                onClick={() => setUserType("seller")}
                                                                                                                                                                                                                                                                                                                                              className="flex items-center gap-1 text-xs px-3 py-1 rounded-full font-medium transition-all"
                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                            background: userType === "seller" ? "var(--accent-color)" : "transparent",
                                                                                                                                                                                                                                                                                                                                                                                            color: userType === "seller" ? "#fff" : "var(--text-color-2)"
                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                    <Store size={12} /> Seller
                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Tabs */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setActiveTab("search")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="flex items-center gap-2 text-xs px-4 py-2 rounded-full font-medium transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: activeTab === "search" ? "var(--accent-color)" : "#f5f0f0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: activeTab === "search" ? "#fff" : "var(--text-color-2)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderColor: activeTab === "search" ? "var(--accent-color)" : "var(--border-color)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Camera size={14} /> Image Search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setActiveTab("chat")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex items-center gap-2 text-xs px-4 py-2 rounded-full font-medium transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: activeTab === "chat" ? "var(--accent-color)" : "#f5f0f0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: activeTab === "chat" ? "#fff" : "var(--text-color-2)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderColor: activeTab === "chat" ? "var(--accent-color)" : "var(--border-color)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <MessageCircle size={14} /> AI Assistant
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Content */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="my-container py-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {activeTab === "search" ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ImageUpload
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onResults={(results, analysis) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setSearchResults(results)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setImageAnalysis(analysis)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {searchResults.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <SearchResults
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                results={searchResults}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                analysis={imageAnalysis}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ChatAssistant userType={userType} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Demo