import { useNavigate } from "react-router-dom"
import { Camera, MessageCircle, Zap, Store } from "lucide-react"

function Home() {
  const navigate = useNavigate()

    return (
        <div className="my-container py-8 animate-fadeIn">

              {/* Header */}
                    <div className="flex items-center justify-between mb-8">
                            <div>
                                      <h1 className="text-2xl" style={{ color: "var(--text-color)" }}>
                                                  Cheque<span style={{ color: "var(--accent-color)" }}>Mart</span>
                                                            </h1>
                                                                      <p className="text-xs m-0" style={{ color: "var(--text-color-2)" }}>
                                                                                  AI Features Demo
                                                                                            </p>
                                                                                                    </div>
                                                                                                            <div
                                                                                                                      className="text-xs px-3 py-1 rounded-full font-medium"
                                                                                                                                style={{ background: "#fff0f0", color: "var(--accent-color)", border: "1px solid #ffcdd2" }}
                                                                                                                                        >
                                                                                                                                                  Demo Preview
                                                                                                                                                          </div>
                                                                                                                                                                </div>

                                                                                                                                                                      {/* Hero */}
                                                                                                                                                                            <div
                                                                                                                                                                                    className="rounded-2xl p-6 mb-6 text-white"
                                                                                                                                                                                            style={{ background: "linear-gradient(135deg, #ff5252, #ff1744)" }}
                                                                                                                                                                                                  >
                                                                                                                                                                                                          <div className="flex items-center gap-2 mb-2">
                                                                                                                                                                                                                    <Zap size={18} />
                                                                                                                                                                                                                              <span className="text-sm font-medium">Powered by Gemini AI</span>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                              <h2 className="text-xl font-bold mb-2 leading-snug">
                                                                                                                                                                                                                                                        Smarter Shopping Starts Here
                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                        <p className="text-sm opacity-90 m-0 leading-relaxed">
                                                                                                                                                                                                                                                                                  Search products by image and get AI-powered store setup advice — all inside ChequeMart.
                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                            onClick={() => navigate("/demo")}
                                                                                                                                                                                                                                                                                                                      className="mt-4 bg-white text-sm font-semibold px-5 py-2 rounded-full"
                                                                                                                                                                                                                                                                                                                                style={{ color: "var(--accent-color)" }}
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                  Try the Demo
                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                      {/* Feature Cards */}
                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-base font-semibold mb-3" style={{ color: "var(--text-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                    What's New
                                                                                                                                                                                                                                                                                                                                                                                          </h3>

                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-col gap-4 mb-6">

                                                                                                                                                                                                                                                                                                                                                                                                        {/* Feature 1 */}
                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-xl p-5 bg-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ boxShadow: "var(--box-shadow)", border: "1px solid var(--border-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-10 h-10 rounded-full flex items-center justify-center mb-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ background: "#fff0f0" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Camera size={20} style={{ color: "var(--accent-color)" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h4 className="text-sm font-semibold mb-1" style={{ color: "var(--text-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Image Scan & Search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs m-0 leading-relaxed" style={{ color: "var(--text-color-2)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Tap the camera icon in the search bar, upload any product photo, and instantly find similar items on ChequeMart.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => navigate("/demo")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-3 text-xs font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ color: "var(--accent-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Try it →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Feature 2 */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="rounded-xl p-5 bg-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ boxShadow: "var(--box-shadow)", border: "1px solid var(--border-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-10 h-10 rounded-full flex items-center justify-center mb-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ background: "#fff0f0" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Store size={20} style={{ color: "var(--accent-color)" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h4 className="text-sm font-semibold mb-1" style={{ color: "var(--text-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AI Store Assistant
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs m-0 leading-relaxed" style={{ color: "var(--text-color-2)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Buyers get instant product help. Sellers paste any store link and get smart layout, color, and arrangement suggestions.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => navigate("/demo?tab=chat")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="mt-3 text-xs font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ color: "var(--accent-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Try it →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Footer note */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-xl p-4 text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ background: "#fff", border: "1px solid var(--border-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center justify-center gap-2 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <MessageCircle size={14} style={{ color: "var(--accent-color)" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs font-semibold" style={{ color: "var(--text-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Dewraber's Tech Institute
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs m-0" style={{ color: "var(--text-color-2)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            This is a demo preview for client approval. Full integration follows after sign-off.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Home