import { useState, useRef } from "react"
import { Camera, Upload, X, Loader } from "lucide-react"
import { analyzeProductImage } from "../services/geminiService"
import mockProducts from "../data/mockProducts"

function ImageUpload({ onResults }) {
  const [preview, setPreview] = useState(null)
    const [loading, setLoading] = useState(false)
      const [error, setError] = useState(null)
        const [dragOver, setDragOver] = useState(false)
          const fileInputRef = useRef(null)

            const handleFile = async (file) => {
                if (!file || !file.type.startsWith("image/")) {
                      setError("Please upload a valid image file.")
                            return
                                }

                                    setError(null)
                                        setPreview(URL.createObjectURL(file))
                                            setLoading(true)

                                                try {
                                                      const analysis = await analyzeProductImage(file)

                                                            // Match mock products by category and keywords
                                                                  const matched = mockProducts.filter((product) => {
                                                                          const categoryMatch = product.category
                                                                                    .toLowerCase()
                                                                                              .includes(analysis.category.toLowerCase())
                                                                                                      const keywordMatch = analysis.keywords.some((kw) =>
                                                                                                                product.name.toLowerCase().includes(kw.toLowerCase()) ||
                                                                                                                          product.description.toLowerCase().includes(kw.toLowerCase())
                                                                                                                                  )
                                                                                                                                          return categoryMatch || keywordMatch
                                                                                                                                                })

                                                                                                                                                      // If no match found, return top 4 from any category
                                                                                                                                                            const results = matched.length > 0 ? matched : mockProducts.slice(0, 4)
                                                                                                                                                                  onResults(results, analysis)
                                                                                                                                                                      } catch (err) {
                                                                                                                                                                            setError("Could not analyze image. Please try again.")
                                                                                                                                                                                } finally {
                                                                                                                                                                                      setLoading(false)
                                                                                                                                                                                          }
                                                                                                                                                                                            }

                                                                                                                                                                                              const handleInputChange = (e) => {
                                                                                                                                                                                                  const file = e.target.files[0]
                                                                                                                                                                                                      if (file) handleFile(file)
                                                                                                                                                                                                        }

                                                                                                                                                                                                          const handleDrop = (e) => {
                                                                                                                                                                                                              e.preventDefault()
                                                                                                                                                                                                                  setDragOver(false)
                                                                                                                                                                                                                      const file = e.dataTransfer.files[0]
                                                                                                                                                                                                                          if (file) handleFile(file)
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                              const clearImage = () => {
                                                                                                                                                                                                                                  setPreview(null)
                                                                                                                                                                                                                                      setError(null)
                                                                                                                                                                                                                                          onResults([], null)
                                                                                                                                                                                                                                              if (fileInputRef.current) fileInputRef.current.value = ""
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                      <div className="mb-6">

                                                                                                                                                                                                                                                            {/* Search bar with camera icon */}
                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                          className="flex items-center gap-3 bg-white rounded-full px-4 py-3 mb-4"
                                                                                                                                                                                                                                                                                  style={{ boxShadow: "var(--box-shadow)", border: "1px solid var(--border-color)" }}
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                          type="text"
                                                                                                                                                                                                                                                                                                                    placeholder="Search products..."
                                                                                                                                                                                                                                                                                                                              className="flex-1 text-sm outline-none bg-transparent"
                                                                                                                                                                                                                                                                                                                                        style={{ color: "var(--text-color)" }}
                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                  onClick={() => fileInputRef.current?.click()}
                                                                                                                                                                                                                                                                                                                                                                            className="flex items-center justify-center w-8 h-8 rounded-full transition-all"
                                                                                                                                                                                                                                                                                                                                                                                      style={{ background: "var(--accent-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                title="Search by image"
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                  <Camera size={16} color="#fff" />
                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Drop zone */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            {!preview && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onDrop={handleDrop}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onDragLeave={() => setDragOver(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => fileInputRef.current?.click()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-2xl p-8 text-center cursor-pointer transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: `2px dashed ${dragOver ? "var(--accent-color)" : "var(--border-color)"}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: dragOver ? "#fff0f0" : "#fff"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-14 h-14 rounded-full flex items-center justify-center mx-auto mb-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ background: "#fff0f0" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Upload size={24} style={{ color: "var(--accent-color)" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm font-medium m-0 mb-1" style={{ color: "var(--text-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Upload a product image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs m-0" style={{ color: "var(--text-color-2)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Tap to browse or drag and drop
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Image preview */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {preview && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="relative rounded-2xl overflow-hidden mb-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ border: "1px solid var(--border-color)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      src={preview}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alt="Uploaded product"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ maxHeight: "220px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={clearImage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="absolute top-3 right-3 w-8 h-8 rounded-full flex items-center justify-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ background: "rgba(0,0,0,0.5)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <X size={16} color="#fff" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="absolute inset-0 flex flex-col items-center justify-center gap-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ background: "rgba(255,255,255,0.85)" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Loader size={28} className="animate-spin" style={{ color: "var(--accent-color)" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm font-medium m-0" style={{ color: "var(--text-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Analyzing image...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Error */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-center mt-2" style={{ color: "var(--accent-color)" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ref={fileInputRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default ImageUpload